# Generated by Django 5.2.7 on 2025-10-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
